# Generated by Django 3.0.4 on 2020-03-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200327_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_name',
            new_name='name',
        ),
    ]
